import { useState } from "react";
import { Check, ChevronDown, ChevronRight, Copy, ExternalLink } from "lucide-react";
import { cn } from "@/utils/cn";
import { MarkdownRenderer } from "@/components/ui/MarkdownRenderer";
import { CodeExcerpt } from "./CodeExcerpt";
import type { SourceRef } from "@/types/sourceTypes";

function basename(path: string): string {
  return path.split("/").pop() || path;
}

function dirname(path: string): string {
  const i = path.lastIndexOf("/");
  return i > 0 ? path.slice(0, i + 1) : "";
}

function lineRange(source: SourceRef): string {
  if (!source.lineStart) return "";
  return source.lineEnd && source.lineEnd !== source.lineStart
    ? `L${source.lineStart}–${source.lineEnd}`
    : `L${source.lineStart}`;
}

function describe(source: SourceRef): { primary: string; dir: string; secondary: string } {
  const path = source.filePath ?? "";
  switch (source.kind) {
    case "code":
      return {
        primary: basename(path),
        dir: dirname(path),
        secondary: [source.symbol, lineRange(source)].filter(Boolean).join(" · "),
      };
    case "documentation":
      return {
        primary: basename(path),
        dir: dirname(path),
        secondary: source.section ? `§ ${source.section.replace(/\s*>\s*/g, " › ")}` : lineRange(source),
      };
    case "summary":
      return {
        primary: source.title ?? "Summary",
        dir: "",
        secondary: source.summaryLevel === "architecture" ? "Architecture summary" : "Component summary",
      };
    case "imports": {
      const anchor = source.imports?.anchor ?? path;
      const importers = source.imports?.dependents.length ?? 0;
      const imported = source.imports?.dependencies.length ?? 0;
      return {
        primary: basename(anchor),
        dir: dirname(anchor),
        secondary: `Import relationships · ${importers} importing · ${imported} imported`,
      };
    }
  }
}

const SPLIT_PART = /\(part \d+\/\d+\)$/;

/**
 * Precise line wording only when the full range is reliably known: the
 * excerpt is file-aligned and the chunk is a whole symbol, not one part of a
 * split one (whose line range covers only that part).
 */
function truncationNote(source: SourceRef): string | null {
  if (!source.truncated) return null;
  if (
    source.kind === "code" &&
    source.excerptStartLine !== undefined &&
    source.lineStart !== undefined &&
    source.lineEnd !== undefined &&
    !SPLIT_PART.test(source.symbol ?? "")
  ) {
    const seenEnd = source.excerptStartLine + source.excerpt.split("\n").length - 1;
    if (seenEnd < source.lineEnd) {
      return `The AI saw lines ${source.excerptStartLine}–${seenEnd} of ${source.lineStart}–${source.lineEnd}.`;
    }
  }
  return "The AI saw a truncated excerpt of this source.";
}

const NOTE = "text-[11px] text-muted-light dark:text-muted-dark";

function SourceBody({ source }: { source: SourceRef }) {
  const note = truncationNote(source);

  if (source.kind === "code") {
    return (
      <>
        <CodeExcerpt code={source.excerpt} filePath={source.filePath} startLine={source.excerptStartLine} />
        {note && <p className={NOTE}>{note}</p>}
      </>
    );
  }

  if (source.kind === "documentation") {
    return (
      <>
        <div className="thin-scrollbar max-h-72 overflow-y-auto rounded-md border border-border-light px-3 py-2 dark:border-border-dark">
          <MarkdownRenderer content={source.excerpt} tone="auto" />
        </div>
        {note && <p className={NOTE}>{note}</p>}
      </>
    );
  }

  if (source.kind === "summary") {
    return (
      <>
        <div className="rounded-md border border-border-light bg-black/[.02] px-3 py-2 dark:border-border-dark dark:bg-white/[.02]">
          <p className="whitespace-pre-wrap text-xs leading-relaxed text-ink-light/90 dark:text-ink-dark/90">
            {source.excerpt}
          </p>
        </div>
        <p className={NOTE}>
          Generated by AI during indexing — a description of the repository, not its source.
          {note ? ` ${note}` : ""}
        </p>
      </>
    );
  }

  const anchor = source.imports?.anchor ?? source.filePath ?? "";
  const rows = [
    ...(source.imports?.dependents ?? []).map((from) => ({ from, to: anchor })),
    ...(source.imports?.dependencies ?? []).map((to) => ({ from: anchor, to })),
  ];
  return (
    <>
      <ul className="space-y-1 font-mono text-[11px]">
        {rows.map(({ from, to }) => (
          <li key={`${from}->${to}`} title={`${from} imports ${to}`} className="truncate">
            <span className="text-ink-light dark:text-ink-dark">{basename(from)}</span>
            <span className="text-muted-light dark:text-muted-dark"> imports → </span>
            <span className="text-ink-light dark:text-ink-dark">{basename(to)}</span>
          </li>
        ))}
      </ul>
      <p className={NOTE}>From the repository's import graph at index time — it may be incomplete.</p>
    </>
  );
}

function SourceActions({ source }: { source: SourceRef }) {
  const [copied, setCopied] = useState(false);
  const canCopy = source.kind === "code" || source.kind === "documentation";
  const url = source.url && /^https:\/\//i.test(source.url) ? source.url : null;
  if (!canCopy && !url) return null;

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(source.excerpt);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      // Clipboard unavailable (insecure context / permissions) — nothing to do.
    }
  };

  const action =
    "inline-flex items-center gap-1 text-muted-light hover:text-ink-light dark:text-muted-dark dark:hover:text-ink-dark";

  return (
    <div className="flex items-center gap-3 text-[11px]">
      {canCopy && (
        <button type="button" onClick={copy} className={action}>
          {copied ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
          {copied ? "Copied" : "Copy"}
        </button>
      )}
      {url && (
        <a href={url} target="_blank" rel="noopener noreferrer" className={action}>
          <ExternalLink className="h-3 w-3" />
          Open on GitHub
          {source.commitSha && <span className="font-mono">@{source.commitSha.slice(0, 7)}</span>}
        </a>
      )}
    </div>
  );
}

interface SourceItemProps {
  source: SourceRef;
  expanded: boolean;
  flashing: boolean;
  onToggle: () => void;
  itemRef: (el: HTMLDivElement | null) => void;
}

export function SourceItem({ source, expanded, flashing, onToggle, itemRef }: SourceItemProps) {
  const { primary, dir, secondary } = describe(source);
  const bodyId = `source-${source.n}-body`;

  return (
    <div ref={itemRef} className={cn("rounded-md transition-shadow", flashing && "ring-2 ring-signal-500/50")}>
      <button
        type="button"
        onClick={onToggle}
        aria-expanded={expanded}
        aria-controls={bodyId}
        className={cn(
          "flex w-full items-start gap-2 rounded-md px-2 py-1.5 text-left",
          expanded ? "bg-black/[.03] dark:bg-white/[.04]" : "hover:bg-black/[.02] dark:hover:bg-white/[.03]",
        )}
      >
        <span className="mt-px w-5 shrink-0 text-right font-mono text-[11px] text-muted-light dark:text-muted-dark">
          {source.n}
        </span>
        <span className="min-w-0 flex-1">
          <span className="flex min-w-0 items-baseline gap-1.5">
            <span
              className={cn(
                "truncate text-xs font-medium text-ink-light dark:text-ink-dark",
                source.kind !== "summary" && "font-mono",
              )}
            >
              {primary}
            </span>
            {source.kind === "summary" && (
              <span className="shrink-0 rounded-sm bg-black/[.05] px-1 py-px text-[10px] text-muted-light dark:bg-white/[.08] dark:text-muted-dark">
                AI summary
              </span>
            )}
            {dir && (
              <span className="min-w-0 truncate text-[11px] text-muted-light dark:text-muted-dark" title={dir}>
                {dir}
              </span>
            )}
          </span>
          {secondary && (
            <span className="block truncate font-mono text-[11px] text-muted-light dark:text-muted-dark">
              {secondary}
            </span>
          )}
        </span>
        {expanded ? (
          <ChevronDown className="mt-0.5 h-3.5 w-3.5 shrink-0 text-muted-light dark:text-muted-dark" />
        ) : (
          <ChevronRight className="mt-0.5 h-3.5 w-3.5 shrink-0 text-muted-light dark:text-muted-dark" />
        )}
      </button>
      {expanded && (
        <div id={bodyId} className="space-y-2 px-2 pb-2 pl-9 pt-1">
          <SourceBody source={source} />
          <SourceActions source={source} />
        </div>
      )}
    </div>
  );
}
