export enum WorkspaceSessionType {
  REVIEW_CHAT = 'REVIEW_CHAT',
  REPOSITORY_QA = 'REPOSITORY_QA',
  INTERVIEW = 'INTERVIEW'
}

export enum LogActivityType {
  REPOSITORY_IMPORTED = 'REPOSITORY_IMPORTED',
  REPOSITORY_INDEXED = 'REPOSITORY_INDEXED',
  PR_REVIEW_STARTED = 'PR_REVIEW_STARTED',
  PR_REVIEW_COMPLETED = 'PR_REVIEW_COMPLETED',
  INTERVIEW_STARTED = 'INTERVIEW_STARTED',
  INTERVIEW_COMPLETED = 'INTERVIEW_COMPLETED',
  REPOSITORY_QA_STARTED = 'REPOSITORY_QA_STARTED'
}